name: FundraiserFusion
version: '${project.version}'
main: fr.gamecreep.fundraiserfusion.FundraiserFusion
api-version: '1.21.4'
load: POSTWORLD
commands:
  info:
    description: Get informations about the plugin !
    usage: /info