name: StreamLabsDonations
version: '${project.version}'
main: fr.gamecreep.streamlabsdonations.StreamLabsDonations
api-version: '1.20'
load: STARTUP
commands:
  test:
    description: Test command to simulate a donation through StreamLabs
    usage: /test [donor-name] [money-amount] [message]